Nd: 100                        # grid
Ctd: 5                         # assumed tumor cells Glu absorbing rate over noralmal cells
Rt: 0.02                       # initial tumor cells growth rate
Rn: 0.04                       # normal cells growth rate
N_division_possibility: 0.001  # Normal cell division possibility(every 1 hour) 
Cg: 1.0                        # Normal cell Glu absorbing
m: 0.60                        # Normal cell density
N_death_rate: 0.005            # Normal cell death rate(every 24 hours) 
T_death_rate: 0.002            # Normal cell death rate(every 24 hours) 
MSR: 1.1                       # MSR 0.025 * 44
Mnr: 0.1                       # Migration normal cells rate
Mtr: 0.5                       # Migration tumor cells rate  
radius: 2                      # radius
total_supply: 10000                   # total supply of Glu


